/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sg.edu.astar.dsi.mergespill;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class mergeinfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"mergeinfo\",\"namespace\":\"sg.edu.astar.dsi.mergespill\",\"fields\":[{\"name\":\"maptaskid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"numberofspill\",\"type\":\"int\"},{\"name\":\"numberofreducer\",\"type\":\"int\"},{\"name\":\"reduceno\",\"type\":\"int\"},{\"name\":\"jobid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String maptaskid;
  @Deprecated public int numberofspill;
  @Deprecated public int numberofreducer;
  @Deprecated public int reduceno;
  @Deprecated public java.lang.String jobid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public mergeinfo() {}

  /**
   * All-args constructor.
   */
  public mergeinfo(java.lang.String maptaskid, java.lang.Integer numberofspill, java.lang.Integer numberofreducer, java.lang.Integer reduceno, java.lang.String jobid) {
    this.maptaskid = maptaskid;
    this.numberofspill = numberofspill;
    this.numberofreducer = numberofreducer;
    this.reduceno = reduceno;
    this.jobid = jobid;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return maptaskid;
    case 1: return numberofspill;
    case 2: return numberofreducer;
    case 3: return reduceno;
    case 4: return jobid;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: maptaskid = (java.lang.String)value$; break;
    case 1: numberofspill = (java.lang.Integer)value$; break;
    case 2: numberofreducer = (java.lang.Integer)value$; break;
    case 3: reduceno = (java.lang.Integer)value$; break;
    case 4: jobid = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'maptaskid' field.
   */
  public java.lang.String getMaptaskid() {
    return maptaskid;
  }

  /**
   * Sets the value of the 'maptaskid' field.
   * @param value the value to set.
   */
  public void setMaptaskid(java.lang.String value) {
    this.maptaskid = value;
  }

  /**
   * Gets the value of the 'numberofspill' field.
   */
  public java.lang.Integer getNumberofspill() {
    return numberofspill;
  }

  /**
   * Sets the value of the 'numberofspill' field.
   * @param value the value to set.
   */
  public void setNumberofspill(java.lang.Integer value) {
    this.numberofspill = value;
  }

  /**
   * Gets the value of the 'numberofreducer' field.
   */
  public java.lang.Integer getNumberofreducer() {
    return numberofreducer;
  }

  /**
   * Sets the value of the 'numberofreducer' field.
   * @param value the value to set.
   */
  public void setNumberofreducer(java.lang.Integer value) {
    this.numberofreducer = value;
  }

  /**
   * Gets the value of the 'reduceno' field.
   */
  public java.lang.Integer getReduceno() {
    return reduceno;
  }

  /**
   * Sets the value of the 'reduceno' field.
   * @param value the value to set.
   */
  public void setReduceno(java.lang.Integer value) {
    this.reduceno = value;
  }

  /**
   * Gets the value of the 'jobid' field.
   */
  public java.lang.String getJobid() {
    return jobid;
  }

  /**
   * Sets the value of the 'jobid' field.
   * @param value the value to set.
   */
  public void setJobid(java.lang.String value) {
    this.jobid = value;
  }

  /** Creates a new mergeinfo RecordBuilder */
  public static sg.edu.astar.dsi.mergespill.mergeinfo.Builder newBuilder() {
    return new sg.edu.astar.dsi.mergespill.mergeinfo.Builder();
  }
  
  /** Creates a new mergeinfo RecordBuilder by copying an existing Builder */
  public static sg.edu.astar.dsi.mergespill.mergeinfo.Builder newBuilder(sg.edu.astar.dsi.mergespill.mergeinfo.Builder other) {
    return new sg.edu.astar.dsi.mergespill.mergeinfo.Builder(other);
  }
  
  /** Creates a new mergeinfo RecordBuilder by copying an existing mergeinfo instance */
  public static sg.edu.astar.dsi.mergespill.mergeinfo.Builder newBuilder(sg.edu.astar.dsi.mergespill.mergeinfo other) {
    return new sg.edu.astar.dsi.mergespill.mergeinfo.Builder(other);
  }
  
  /**
   * RecordBuilder for mergeinfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<mergeinfo>
    implements org.apache.avro.data.RecordBuilder<mergeinfo> {

    private java.lang.String maptaskid;
    private int numberofspill;
    private int numberofreducer;
    private int reduceno;
    private java.lang.String jobid;

    /** Creates a new Builder */
    private Builder() {
      super(sg.edu.astar.dsi.mergespill.mergeinfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sg.edu.astar.dsi.mergespill.mergeinfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.maptaskid)) {
        this.maptaskid = data().deepCopy(fields()[0].schema(), other.maptaskid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numberofspill)) {
        this.numberofspill = data().deepCopy(fields()[1].schema(), other.numberofspill);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numberofreducer)) {
        this.numberofreducer = data().deepCopy(fields()[2].schema(), other.numberofreducer);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reduceno)) {
        this.reduceno = data().deepCopy(fields()[3].schema(), other.reduceno);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.jobid)) {
        this.jobid = data().deepCopy(fields()[4].schema(), other.jobid);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing mergeinfo instance */
    private Builder(sg.edu.astar.dsi.mergespill.mergeinfo other) {
            super(sg.edu.astar.dsi.mergespill.mergeinfo.SCHEMA$);
      if (isValidValue(fields()[0], other.maptaskid)) {
        this.maptaskid = data().deepCopy(fields()[0].schema(), other.maptaskid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numberofspill)) {
        this.numberofspill = data().deepCopy(fields()[1].schema(), other.numberofspill);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numberofreducer)) {
        this.numberofreducer = data().deepCopy(fields()[2].schema(), other.numberofreducer);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reduceno)) {
        this.reduceno = data().deepCopy(fields()[3].schema(), other.reduceno);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.jobid)) {
        this.jobid = data().deepCopy(fields()[4].schema(), other.jobid);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'maptaskid' field */
    public java.lang.String getMaptaskid() {
      return maptaskid;
    }
    
    /** Sets the value of the 'maptaskid' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder setMaptaskid(java.lang.String value) {
      validate(fields()[0], value);
      this.maptaskid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'maptaskid' field has been set */
    public boolean hasMaptaskid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'maptaskid' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder clearMaptaskid() {
      maptaskid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'numberofspill' field */
    public java.lang.Integer getNumberofspill() {
      return numberofspill;
    }
    
    /** Sets the value of the 'numberofspill' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder setNumberofspill(int value) {
      validate(fields()[1], value);
      this.numberofspill = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'numberofspill' field has been set */
    public boolean hasNumberofspill() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'numberofspill' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder clearNumberofspill() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'numberofreducer' field */
    public java.lang.Integer getNumberofreducer() {
      return numberofreducer;
    }
    
    /** Sets the value of the 'numberofreducer' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder setNumberofreducer(int value) {
      validate(fields()[2], value);
      this.numberofreducer = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'numberofreducer' field has been set */
    public boolean hasNumberofreducer() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'numberofreducer' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder clearNumberofreducer() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'reduceno' field */
    public java.lang.Integer getReduceno() {
      return reduceno;
    }
    
    /** Sets the value of the 'reduceno' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder setReduceno(int value) {
      validate(fields()[3], value);
      this.reduceno = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'reduceno' field has been set */
    public boolean hasReduceno() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'reduceno' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder clearReduceno() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'jobid' field */
    public java.lang.String getJobid() {
      return jobid;
    }
    
    /** Sets the value of the 'jobid' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder setJobid(java.lang.String value) {
      validate(fields()[4], value);
      this.jobid = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'jobid' field has been set */
    public boolean hasJobid() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'jobid' field */
    public sg.edu.astar.dsi.mergespill.mergeinfo.Builder clearJobid() {
      jobid = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public mergeinfo build() {
      try {
        mergeinfo record = new mergeinfo();
        record.maptaskid = fieldSetFlags()[0] ? this.maptaskid : (java.lang.String) defaultValue(fields()[0]);
        record.numberofspill = fieldSetFlags()[1] ? this.numberofspill : (java.lang.Integer) defaultValue(fields()[1]);
        record.numberofreducer = fieldSetFlags()[2] ? this.numberofreducer : (java.lang.Integer) defaultValue(fields()[2]);
        record.reduceno = fieldSetFlags()[3] ? this.reduceno : (java.lang.Integer) defaultValue(fields()[3]);
        record.jobid = fieldSetFlags()[4] ? this.jobid : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
